config/routes.rb
SavedoMonumentCollections::Application.routes.draw do
  resources :categories

  devise_for :admins
  devise_for :users

  root to: 'monuments#index'

  resources :monuments
  resources :collections
  post 'monuments/new/second_part' => 'monuments#second_part'
  post 'monuments/new/confirmation' => 'monuments#confirmation'

end

app/models/ability.rb
class Ability 
  include CanCan::Ability
  # include Devise::Controllers::Helpers

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
      # user ||= User.new # guest user (not logged in)

      if user
        can :update, :all, user_id: user.id
        can :read, :all
        can :create, :all
      elsif !user
        user = User.new
        can :read, :all
      elsif user.admin?
        can :manage, :all          
      end
    
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true
end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_and_belongs_to_many :monuments
	belongs_to :user
	
	validates :name, presence: true
	# validates :monuments, presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :monument
	has_attached_file :photo

	validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/monument.rb
class Monument < ActiveRecord::Base
	has_and_belongs_to_many :collections
	has_many :images

	accepts_nested_attributes_for :images
	validates :name, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # include Devise::Controllers::Helpers

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :collections

  attr_reader :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied."
    redirect_to root_url
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

	load_and_authorize_resource
	before_action :set_collection, only: [:show, :edit, :update, :destroy]
	respond_to :html

	def index
	  @categories = Collection.all
	  respond_with(@categories)
	end

	def show
	  respond_with(@collection)
	end

	def new
	  @collection = Collection.new
	  respond_with(@collection)
	end

	def edit
	end

	def create
	  @collection = Collection.new(collection_params)
	  @collection.save
	  respond_with(@collection)
	end

	def update
	  @collection.update(collection_params)
	  respond_with(@collection)
	end

	def destroy
	  @collection.destroy
	  respond_with(@collection)
	end

	private
	  def set_collection
	    @collection = Collection.find(params[:id])
	  end

	  def collection_params
	    params.require(:collection).permit(:name)
	  end
end

app/controllers/monuments_controller.rb
class MonumentsController < ApplicationController

	before_action :set_monument, only: [:show, :edit, :update, :destroy]
	respond_to :html

	def index
		@monuments = Monument.all
	end

	def new
		@monument = Monument.new
	end

	def show
		respond_with(@monument)
	end

	def second_part
		@monument_before = monument_params
		@monument = Monument.new
	end

	def confirmation
		@monument = monument_params
	end

	def create
		@monument = Monument.new(monument_params)
		
		respond_to do |format|
		  if @monument.save
		  	if params[:images]
		  		puts "It has #{params[:images].size}images"
		  		# binding.pry
		  		params[:images][:images].each do |img|
		  			@monument.images.create(photo: img)
		  			# binding.pry
		  			# @monument.images.save
		  		end
		  		# @monument.images.each do |image|
		  		# 	@monument.photo = image
		  		# 	puts @monument.to_json
		  		# 	@monument.photo.save
		  		# end
		  	end
		    format.html { redirect_to @monument, notice: 'monument was successfully created.' }
		    format.json { render action: 'show', status: :created, location: @monument }
		  else
		    format.html { render action: 'new' }
		    format.json { render json: @monument.errors, status: :unprocessable_entity }
		  end
		end
	end
	def edit

	end

	def update
	  respond_to do |format|
	    if @monument.update(monument_params)
	      format.html { redirect_to @monument, notice: 'User was successfully updated.' }
	      format.json { head :no_content }
	      if @monument.image
	      	@monument.image.each do |image|
	      		Image.create(@monument.image)
	      	end
	      end
	    else
	      format.html { render action: 'edit' }
	      format.json { render json: @monument.errors, status: :unprocessable_entity }
	    end
	  end
	end

	# DELETE /users/1
	# DELETE /users/1.json
	def destroy
	  @monument.destroy
	  respond_to do |format|
	    format.html { redirect_to users_url }
	    format.json { head :no_content }
	  end
	end


	private

	def set_monument
	  @monument = Monument.find(params[:id])
	end

	def monument_params
		params.require(:monument).permit(:name, :description, :images)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/monuments_helper.rb
module MonumentsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<h1>Listing collections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SavedoMonumentCollections</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Title</a>
		</div>
	
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">Link</a></li>
				<li><a href="#">Link</a></li>
			</ul>
			<% flash.each do |type, message| %>
			  	<%= content_tag :div, message, :class => "flash #{type}" %>
			<% end %>
			<div class='signin' style ='float:right;padding-top:15px'>
				<% if user_signed_in? %>
						 Welcome <%= current_user.email %> not you? <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
					<% else %>
						<%= link_to "Sign In", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %>
				<% end %>
			</div>
		</div>


		
		<!-- /.navbar-collapse -->
	</nav>
<%= yield %>

</body>
</html>

app/views/monuments/confirmation.html.erb
This is the confirmation

<%= @monument.size %>
<p>The Description is : <%= @monument_before['description'] %></p>

app/views/monuments/index.html.erb
This is the index file

<%= @monuments.each do |monument| %>

	<%= monument.name %>
	<%= monument.description %>

<% end %>

<% if can?(:read, @monuments) %>
	This user can read stuff
<% end %>

<% if user_signed_in? %>
	The user is signed in!
<% end %>

app/views/monuments/new.html.erb
<% if @monument.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@monument.errors.count, "error") %> prohibited this review from being saved:</h2>

    <ul>
    <% @monument.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<div class="formcontainer">
  <%= form_for @monument, :class => 'example-basic', :html => {:multipart => true} do |f| %>
    <div id="example-basic">
      <h3>Basic Info</h3>
      <section>
        <h2>Monument Data</h2>
        <%= f.label :name, "Name" %>
        <%= f.text_field :name %>
        <br>
        <%= f.label :description, "Description" %>
        <br>
        <%= f.text_area :description %>
      </section>
      <h3>Images</h3>
      <section>
        <%= fields_for :images do |img| %>
          <%= img.label :images, "Image" %>
          <%= img.file_field :images, :multiple => true %>
        <% end %>                
      </section>
      <h3>Confirm</h3>
      <section>
        <p>The Name is: <span id='checkname'></span></p>
        <p>The next and previous buttons help you to navigate through your content.</p>
        <%= submit_tag "Save changes", :id => "submit", :name => "submit", :class => "form_submit", :disabled => false, :disable_with => "Please wait..." %>
      </section>
    </div>  
  <% end %>
  
</div>


<script>
    $("#example-basic").steps({
        headerTag: "h3",
        bodyTag: "section",
        transitionEffect: "slideLeft",
        autoFocus: true
      });
  
</script>

app/views/monuments/second_part.html.erb
<h2>This is the second part of the form</h2> 



<p>The name is : <%= @monument_before['name'] %></p>

<p>The Description is : <%= @monument_before['description'] %></p>


<%= form_for @monument, :url =>url_for(:controller => 'monuments', :action => 'confirmation') do |f| %>
  <% if @monument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monument.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @monument.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  	<%= f.file_field :image, type: :file, multiple: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>